services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${ME_CONFIG_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: ${ME_CONFIG_BASICAUTH}

volumes:
  mongodb_data:
    driver: local
    # The `driver_opts` section specifies additional options for the volume driver.
    # - `o: bind`: Indicates that the volume is a bind mount.
    # - `type: none`: Specifies that no specific filesystem type is enforced.
    # - `device: /home/yves/dev/yves/blockchain/mongodb_data`: Defines the host path to be mounted as the volume.
    # This configuration binds the specified host directory to the container, allowing data persistence.
    driver_opts:
      o: bind
      type: none
      device: /home/yves/dev/yves/blockchain/mongodb_data